version: '3'

services:
  api:
    build: ./gameapi
    volumes:
      - ./gameapi/app:/app/app
    command: /start-reload.sh
    env_file:
      - .env
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_P}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/sql:/docker-entrypoint-initdb.d
  front:
    build: ./gameprofile # Dockerfileの場所
    working_dir: /app # ホストOSとコンテナ内でソースコードを共有する
    command: yarn dev
    env_file:
      - .env
    environment:
      - DEV_MODE=1
    volumes:
      - ./gameprofile:/app
    ports:
      - "127.0.0.1:3000:3000"
    tty: true # コンテナ起動後、StatusがExitにならないようttyの設定
    depends_on:
      - api
